name = "Nuclear Revolution"
author = "Nifylau"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d24de59ceb196f815ca10ed975cd9976ed81e2cca0c7c553b554a1744918f406"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
