name = "Nuclear Revolution"
author = "Nifylau"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa964ee7288f0dd79c30467759a7595cd80d414266a6b1a47b784826854d6658"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
