name = "Nuclear Revolution"
author = "Nifylau"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dca9565fad1f4856635e5034a6cf0659b2bad37a4ebff6a01b4000b0af4d418"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
